import type { NavItem, Tool } from '@/types'
import navConfig from '../../config/navigation.json'

export const navItems: NavItem[] = navConfig as NavItem[]

export const tools: Tool[] = [
  // ── Pickers ──
  { id: 'color-picker', name: 'Color Picker', description: 'Pick and fine-tune colors with an interactive visual color picker interface.', category: 'picker', slug: '/color-picker/', icon: 'eyedropper' },
  { id: 'eye-dropper-tool', name: 'Eye Dropper Tool', description: 'Sample any color from your screen with a precision eye dropper tool.', category: 'picker', slug: '/eye-dropper-tool/', icon: 'eyedropper' },
  { id: 'screen-color-picker', name: 'Screen Color Picker', description: 'Pick colors directly from anywhere on your screen in real time.', category: 'picker', slug: '/screen-color-picker/', icon: 'eyedropper' },
  { id: 'hex-color-picker', name: 'HEX Color Picker', description: 'Pick and preview colors using hexadecimal color code input.', category: 'picker', slug: '/hex-color-picker/', icon: 'eyedropper' },
  { id: 'rgb-color-picker', name: 'RGB Color Picker', description: 'Select colors by adjusting red, green, and blue channel values.', category: 'picker', slug: '/rgb-color-picker/', icon: 'eyedropper' },
  { id: 'hsl-color-picker', name: 'HSL Color Picker', description: 'Pick colors intuitively using hue, saturation, and lightness sliders.', category: 'picker', slug: '/hsl-color-picker/', icon: 'eyedropper' },
  { id: 'hsv-color-picker', name: 'HSV Color Picker', description: 'Choose colors with hue, saturation, and value controls for precision.', category: 'picker', slug: '/hsv-color-picker/', icon: 'eyedropper' },
  { id: 'cmyk-color-picker', name: 'CMYK Color Picker', description: 'Pick colors in CMYK mode for print-ready color selection.', category: 'picker', slug: '/cmyk-color-picker/', icon: 'eyedropper' },
  { id: 'lab-color-picker', name: 'LAB Color Picker', description: 'Select colors using the perceptually uniform LAB color space.', category: 'picker', slug: '/lab-color-picker/', icon: 'eyedropper' },
  { id: 'lch-color-picker', name: 'LCH Color Picker', description: 'Pick colors with lightness, chroma, and hue controls for natural selection.', category: 'picker', slug: '/lch-color-picker/', icon: 'eyedropper' },
  { id: 'oklab-color-picker', name: 'OKLab Color Picker', description: 'Pick colors using the modern OKLab perceptually uniform color space.', category: 'picker', slug: '/oklab-color-picker/', icon: 'eyedropper' },
  { id: 'oklch-color-picker', name: 'OKLCH Color Picker', description: 'Select colors with OKLCH lightness, chroma, and hue for accurate results.', category: 'picker', slug: '/oklch-color-picker/', icon: 'eyedropper' },
  { id: 'hwb-color-picker', name: 'HWB Color Picker', description: 'Pick colors using hue, whiteness, and blackness sliders for simplicity.', category: 'picker', slug: '/hwb-color-picker/', icon: 'eyedropper' },
  { id: 'rgba-color-picker', name: 'RGBA Color Picker', description: 'Pick colors with RGB channels plus an alpha transparency slider.', category: 'picker', slug: '/rgba-color-picker/', icon: 'eyedropper' },
  { id: 'hsla-color-picker', name: 'HSLA Color Picker', description: 'Select colors using HSL with an alpha channel for transparency control.', category: 'picker', slug: '/hsla-color-picker/', icon: 'eyedropper' },
  { id: 'alpha-color-picker', name: 'Alpha Color Picker', description: 'Fine-tune the transparency of any color with an alpha channel picker.', category: 'picker', slug: '/alpha-color-picker/', icon: 'picker' },
  { id: 'gradient-color-picker', name: 'Gradient Color Picker', description: 'Pick multiple colors for seamless gradient creation and editing.', category: 'picker', slug: '/gradient-color-picker/', icon: 'gradient' },
  { id: 'multi-color-picker', name: 'Multi Color Picker', description: 'Pick and manage several colors at once for complex palettes.', category: 'picker', slug: '/multi-color-picker/', icon: 'picker' },
  { id: 'image-color-picker', name: 'Image Color Picker', description: 'Upload an image and pick colors from any pixel within it.', category: 'picker', slug: '/image-color-picker/', icon: 'image' },
  { id: 'website-color-picker', name: 'Website Color Picker', description: 'Extract and pick colors from any website by entering its URL.', category: 'picker', slug: '/website-color-picker/', icon: 'image' },
  { id: 'transparent-color-picker', name: 'Transparent Color Picker', description: 'Pick and preview colors with varying levels of transparency.', category: 'picker', slug: '/transparent-color-picker/', icon: 'picker' },
  { id: 'random-color-picker', name: 'Random Color Picker', description: 'Discover random colors with a click for creative inspiration.', category: 'picker', slug: '/random-color-picker/', icon: 'wand' },
  { id: 'browser-color-picker', name: 'Browser Color Picker', description: 'Use a native-style color picker adapted for web workflows.', category: 'picker', slug: '/browser-color-picker/', icon: 'eyedropper' },
  { id: 'pixel-color-picker', name: 'Pixel Color Picker', description: 'Zoom into images and pick individual pixel colors with precision.', category: 'picker', slug: '/pixel-color-picker/', icon: 'eyedropper' },
  { id: 'magnifier-color-picker', name: 'Magnifier Color Picker', description: 'Magnify screen areas to pick exact colors with pixel-level accuracy.', category: 'picker', slug: '/magnifier-color-picker/', icon: 'eyedropper' },

  // ── Converters ──
  { id: 'hex-to-rgb', name: 'HEX to RGB', description: 'Convert hexadecimal color codes to RGB values instantly.', category: 'converter', slug: '/hex-to-rgb/', icon: 'palette' },
  { id: 'rgb-to-hex', name: 'RGB to HEX', description: 'Convert RGB color values to hexadecimal format with one click.', category: 'converter', slug: '/rgb-to-hex/', icon: 'palette' },
  { id: 'hex-to-hsl', name: 'HEX to HSL', description: 'Convert hex colors to HSL (Hue, Saturation, Lightness) representation.', category: 'converter', slug: '/hex-to-hsl/', icon: 'palette' },
  { id: 'hsl-to-hex', name: 'HSL to HEX', description: 'Convert HSL values back to hexadecimal color codes.', category: 'converter', slug: '/hsl-to-hex/', icon: 'palette' },
  { id: 'hex-to-hsv', name: 'HEX to HSV', description: 'Convert hex colors to HSV (Hue, Saturation, Value) color space.', category: 'converter', slug: '/hex-to-hsv/', icon: 'palette' },
  { id: 'hsv-to-hex', name: 'HSV to HEX', description: 'Convert HSV values back to hexadecimal color codes.', category: 'converter', slug: '/hsv-to-hex/', icon: 'palette' },
  { id: 'rgb-to-hsl', name: 'RGB to HSL', description: 'Convert RGB values to HSL color representation effortlessly.', category: 'converter', slug: '/rgb-to-hsl/', icon: 'palette' },
  { id: 'hsl-to-rgb', name: 'HSL to RGB', description: 'Convert HSL color values back to RGB format.', category: 'converter', slug: '/hsl-to-rgb/', icon: 'palette' },
  { id: 'rgb-to-hsv', name: 'RGB to HSV', description: 'Convert RGB values to HSV color space for design workflows.', category: 'converter', slug: '/rgb-to-hsv/', icon: 'palette' },
  { id: 'hsv-to-rgb', name: 'HSV to RGB', description: 'Convert HSV color values back to RGB format.', category: 'converter', slug: '/hsv-to-rgb/', icon: 'palette' },
  { id: 'rgb-to-cmyk', name: 'RGB to CMYK', description: 'Convert RGB colors to CMYK for print-ready color output.', category: 'converter', slug: '/rgb-to-cmyk/', icon: 'palette' },
  { id: 'cmyk-to-rgb', name: 'CMYK to RGB', description: 'Convert CMYK values to RGB for digital display use.', category: 'converter', slug: '/cmyk-to-rgb/', icon: 'palette' },
  { id: 'hex-to-cmyk', name: 'HEX to CMYK', description: 'Convert hex color codes to CMYK values for print design.', category: 'converter', slug: '/hex-to-cmyk/', icon: 'palette' },
  { id: 'cmyk-to-hex', name: 'CMYK to HEX', description: 'Convert CMYK values to hexadecimal color codes.', category: 'converter', slug: '/cmyk-to-hex/', icon: 'palette' },
  { id: 'hex-to-lab', name: 'HEX to LAB', description: 'Convert hex colors to the perceptually uniform LAB color space.', category: 'converter', slug: '/hex-to-lab/', icon: 'code' },
  { id: 'lab-to-hex', name: 'LAB to HEX', description: 'Convert LAB color values back to hexadecimal format.', category: 'converter', slug: '/lab-to-hex/', icon: 'code' },
  { id: 'rgb-to-lab', name: 'RGB to LAB', description: 'Convert RGB values to the LAB color space for accurate analysis.', category: 'converter', slug: '/rgb-to-lab/', icon: 'code' },
  { id: 'lab-to-rgb', name: 'LAB to RGB', description: 'Convert LAB color values to RGB for digital display.', category: 'converter', slug: '/lab-to-rgb/', icon: 'code' },
  { id: 'hex-to-lch', name: 'HEX to LCH', description: 'Convert hex colors to LCH (Lightness, Chroma, Hue) format.', category: 'converter', slug: '/hex-to-lch/', icon: 'code' },
  { id: 'lch-to-hex', name: 'LCH to HEX', description: 'Convert LCH color values back to hexadecimal color codes.', category: 'converter', slug: '/lch-to-hex/', icon: 'code' },
  { id: 'rgb-to-lch', name: 'RGB to LCH', description: 'Convert RGB values to LCH color representation.', category: 'converter', slug: '/rgb-to-lch/', icon: 'code' },
  { id: 'lch-to-rgb', name: 'LCH to RGB', description: 'Convert LCH color values back to RGB format.', category: 'converter', slug: '/lch-to-rgb/', icon: 'code' },
  { id: 'hex-to-oklab', name: 'HEX to OKLab', description: 'Convert hex colors to the modern OKLab color space.', category: 'converter', slug: '/hex-to-oklab/', icon: 'code' },
  { id: 'oklab-to-hex', name: 'OKLab to HEX', description: 'Convert OKLab color values back to hexadecimal format.', category: 'converter', slug: '/oklab-to-hex/', icon: 'code' },
  { id: 'rgb-to-oklab', name: 'RGB to OKLab', description: 'Convert RGB values to the OKLab perceptually uniform color space.', category: 'converter', slug: '/rgb-to-oklab/', icon: 'code' },
  { id: 'oklab-to-rgb', name: 'OKLab to RGB', description: 'Convert OKLab color values to RGB for display.', category: 'converter', slug: '/oklab-to-rgb/', icon: 'code' },
  { id: 'hex-to-oklch', name: 'HEX to OKLCH', description: 'Convert hex colors to OKLCH (Lightness, Chroma, Hue) format.', category: 'converter', slug: '/hex-to-oklch/', icon: 'code' },
  { id: 'oklch-to-hex', name: 'OKLCH to HEX', description: 'Convert OKLCH color values back to hexadecimal codes.', category: 'converter', slug: '/oklch-to-hex/', icon: 'code' },
  { id: 'rgb-to-oklch', name: 'RGB to OKLCH', description: 'Convert RGB values to OKLCH color representation.', category: 'converter', slug: '/rgb-to-oklch/', icon: 'code' },
  { id: 'oklch-to-rgb', name: 'OKLCH to RGB', description: 'Convert OKLCH color values back to RGB format.', category: 'converter', slug: '/oklch-to-rgb/', icon: 'code' },
  { id: 'rgb-to-hwb', name: 'RGB to HWB', description: 'Convert RGB values to HWB (Hue, Whiteness, Blackness) format.', category: 'converter', slug: '/rgb-to-hwb/', icon: 'palette' },
  { id: 'hwb-to-rgb', name: 'HWB to RGB', description: 'Convert HWB color values back to RGB format.', category: 'converter', slug: '/hwb-to-rgb/', icon: 'palette' },
  { id: 'hex-to-hwb', name: 'HEX to HWB', description: 'Convert hex color codes to HWB representation.', category: 'converter', slug: '/hex-to-hwb/', icon: 'palette' },
  { id: 'hwb-to-hex', name: 'HWB to HEX', description: 'Convert HWB values to hexadecimal color codes.', category: 'converter', slug: '/hwb-to-hex/', icon: 'palette' },
  { id: 'rgba-to-hex', name: 'RGBA to HEX', description: 'Convert RGBA values with alpha to hexadecimal format.', category: 'converter', slug: '/rgba-to-hex/', icon: 'palette' },
  { id: 'hex-to-rgba', name: 'HEX to RGBA', description: 'Convert hex codes to RGBA with alpha channel support.', category: 'converter', slug: '/hex-to-rgba/', icon: 'palette' },
  { id: 'hsla-to-hex', name: 'HSLA to HEX', description: 'Convert HSLA values with alpha to hexadecimal color codes.', category: 'converter', slug: '/hsla-to-hex/', icon: 'palette' },
  { id: 'hex-to-hsla', name: 'HEX to HSLA', description: 'Convert hex colors to HSLA with alpha transparency.', category: 'converter', slug: '/hex-to-hsla/', icon: 'palette' },
  { id: 'css-color-converter', name: 'CSS Color Converter', description: 'Convert between all CSS color formats including named colors and functions.', category: 'converter', slug: '/css-color-converter/', icon: 'code' },
  { id: 'tailwind-color-converter', name: 'Tailwind Color Converter', description: 'Convert between Tailwind CSS color names and their hex values.', category: 'converter', slug: '/tailwind-color-converter/', icon: 'code' },
  { id: 'material-color-converter', name: 'Material Color Converter', description: 'Convert Material Design color names to their corresponding hex codes.', category: 'converter', slug: '/material-color-converter/', icon: 'code' },
  { id: 'android-xml-color-converter', name: 'Android XML Color Converter', description: 'Convert colors to and from Android XML color resource format.', category: 'converter', slug: '/android-xml-color-converter/', icon: 'code' },
  { id: 'swift-uicolor-converter', name: 'Swift UIColor Converter', description: 'Convert colors to and from Swift UIColor initializer syntax.', category: 'converter', slug: '/swift-uicolor-converter/', icon: 'code' },
  { id: 'flutter-color-converter', name: 'Flutter Color Converter', description: 'Convert colors to and from Flutter Color constructor syntax.', category: 'converter', slug: '/flutter-color-converter/', icon: 'code' },
  { id: 'kotlin-color-converter', name: 'Kotlin Color Converter', description: 'Convert colors to and from Kotlin Android Color syntax.', category: 'converter', slug: '/kotlin-color-converter/', icon: 'code' },
  { id: 'java-color-converter', name: 'Java Color Converter', description: 'Convert colors to and from Java Color class instantiation.', category: 'converter', slug: '/java-color-converter/', icon: 'code' },
  { id: 'csharp-color-converter', name: 'C# Color Converter', description: 'Convert colors to and from C# System.Drawing.Color syntax.', category: 'converter', slug: '/csharp-color-converter/', icon: 'code' },
  { id: 'python-color-converter', name: 'Python Color Converter', description: 'Convert colors to and from Python color representation formats.', category: 'converter', slug: '/python-color-converter/', icon: 'code' },
  { id: 'css-variable-converter', name: 'CSS Variable Converter', description: 'Convert color values to and from CSS custom property syntax.', category: 'converter', slug: '/css-variable-converter/', icon: 'code' },
  { id: 'json-color-converter', name: 'JSON Color Converter', description: 'Convert colors to and from structured JSON color format.', category: 'converter', slug: '/json-color-converter/', icon: 'code' },
  { id: 'scss-color-converter', name: 'SCSS Color Converter', description: 'Convert colors to and from SCSS variable and function syntax.', category: 'converter', slug: '/scss-color-converter/', icon: 'code' },
  { id: 'less-color-converter', name: 'LESS Color Converter', description: 'Convert colors to and from LESS variable and function syntax.', category: 'converter', slug: '/less-color-converter/', icon: 'code' },
  { id: 'color-format-detector', name: 'Color Format Detector', description: 'Automatically detect the format of any color string you paste.', category: 'converter', slug: '/color-format-detector/', icon: 'search' },
  { id: 'universal-color-converter', name: 'Universal Color Converter', description: 'Convert between any two color formats with a single unified tool.', category: 'converter', slug: '/universal-color-converter/', icon: 'wand' },
  { id: 'batch-color-converter', name: 'Batch Color Converter', description: 'Convert multiple colors at once between different color formats.', category: 'converter', slug: '/batch-color-converter/', icon: 'wand' },

  // ── Palettes ──
  { id: 'random-palette-generator', name: 'Random Palette Generator', description: 'Generate random color palettes for instant design inspiration.', category: 'palette', slug: '/random-palette-generator/', icon: 'wand' },
  { id: 'ai-palette-generator', name: 'AI Palette Generator', description: 'Let AI generate harmonious color palettes based on your description.', category: 'palette', slug: '/ai-palette-generator/', icon: 'wand' },
  { id: 'brand-palette-generator', name: 'Brand Palette Generator', description: 'Create professional brand color palettes for your business identity.', category: 'palette', slug: '/brand-palette-generator/', icon: 'layout' },
  { id: 'ui-palette-generator', name: 'UI Palette Generator', description: 'Generate cohesive color palettes optimized for user interface design.', category: 'palette', slug: '/ui-palette-generator/', icon: 'layout' },
  { id: 'material-palette-generator', name: 'Material Palette Generator', description: 'Generate Material Design 3 color palettes from a seed color.', category: 'palette', slug: '/material-palette-generator/', icon: 'swatch' },
  { id: 'tailwind-palette-generator', name: 'Tailwind Palette Generator', description: 'Create Tailwind CSS compatible color palettes with all shades.', category: 'palette', slug: '/tailwind-palette-generator/', icon: 'swatch' },
  { id: 'bootstrap-palette-generator', name: 'Bootstrap Palette Generator', description: 'Generate Bootstrap-compatible color palettes for your projects.', category: 'palette', slug: '/bootstrap-palette-generator/', icon: 'swatch' },
  { id: 'dark-theme-palette', name: 'Dark Theme Palette', description: 'Generate beautiful dark mode color palettes for apps and websites.', category: 'palette', slug: '/dark-theme-palette/', icon: 'sun' },
  { id: 'light-theme-palette', name: 'Light Theme Palette', description: 'Generate clean and bright light mode color palettes for interfaces.', category: 'palette', slug: '/light-theme-palette/', icon: 'sun' },
  { id: 'pastel-palette-generator', name: 'Pastel Palette Generator', description: 'Create soft and muted pastel color palettes for gentle designs.', category: 'palette', slug: '/pastel-palette-generator/', icon: 'swatch' },
  { id: 'neon-palette-generator', name: 'Neon Palette Generator', description: 'Generate vibrant neon color palettes for bold and energetic designs.', category: 'palette', slug: '/neon-palette-generator/', icon: 'swatch' },
  { id: 'vintage-palette-generator', name: 'Vintage Palette Generator', description: 'Create retro-inspired vintage color palettes with nostalgic charm.', category: 'palette', slug: '/vintage-palette-generator/', icon: 'swatch' },
  { id: 'retro-palette-generator', name: 'Retro Palette Generator', description: 'Generate throwback retro color palettes from past design eras.', category: 'palette', slug: '/retro-palette-generator/', icon: 'swatch' },
  { id: 'nature-palette-generator', name: 'Nature Palette Generator', description: 'Create color palettes inspired by natural landscapes and environments.', category: 'palette', slug: '/nature-palette-generator/', icon: 'swatch' },
  { id: 'ocean-palette-generator', name: 'Ocean Palette Generator', description: 'Generate ocean-inspired color palettes from deep blues to seafoam.', category: 'palette', slug: '/ocean-palette-generator/', icon: 'swatch' },
  { id: 'sunset-palette-generator', name: 'Sunset Palette Generator', description: 'Create warm and dramatic sunset-inspired color palettes.', category: 'palette', slug: '/sunset-palette-generator/', icon: 'swatch' },
  { id: 'autumn-palette-generator', name: 'Autumn Palette Generator', description: 'Generate fall-inspired palettes with warm oranges, reds, and golds.', category: 'palette', slug: '/autumn-palette-generator/', icon: 'swatch' },
  { id: 'spring-palette-generator', name: 'Spring Palette Generator', description: 'Create fresh and vibrant spring-inspired color palettes.', category: 'palette', slug: '/spring-palette-generator/', icon: 'swatch' },
  { id: 'winter-palette-generator', name: 'Winter Palette Generator', description: 'Generate cool and crisp winter-inspired color palettes.', category: 'palette', slug: '/winter-palette-generator/', icon: 'swatch' },
  { id: 'summer-palette-generator', name: 'Summer Palette Generator', description: 'Create bright and sunny summer-inspired color palettes.', category: 'palette', slug: '/summer-palette-generator/', icon: 'swatch' },
  { id: 'monochromatic-palette', name: 'Monochromatic Palette', description: 'Generate harmonious monochromatic color schemes from a single hue.', category: 'palette', slug: '/monochromatic-palette/', icon: 'layout' },
  { id: 'analogous-palette', name: 'Analogous Palette', description: 'Create smooth analogous color schemes with adjacent hue combinations.', category: 'palette', slug: '/analogous-palette/', icon: 'layout' },
  { id: 'complementary-palette', name: 'Complementary Palette', description: 'Generate high-contrast complementary color schemes.', category: 'palette', slug: '/complementary-palette/', icon: 'contrast' },
  { id: 'split-complementary-palette', name: 'Split Complementary Palette', description: 'Create balanced split-complementary color schemes for visual interest.', category: 'palette', slug: '/split-complementary-palette/', icon: 'contrast' },
  { id: 'triadic-palette', name: 'Triadic Palette', description: 'Generate vibrant triadic color schemes with three evenly spaced hues.', category: 'palette', slug: '/triadic-palette/', icon: 'layout' },
  { id: 'tetradic-palette', name: 'Tetradic Palette', description: 'Create rich tetradic color schemes using four harmoniously arranged colors.', category: 'palette', slug: '/tetradic-palette/', icon: 'layout' },
  { id: 'square-palette', name: 'Square Palette', description: 'Generate balanced square color schemes with four evenly spaced colors.', category: 'palette', slug: '/square-palette/', icon: 'layout' },
  { id: 'rainbow-palette', name: 'Rainbow Palette', description: 'Create vibrant rainbow color palettes spanning the full color spectrum.', category: 'palette', slug: '/rainbow-palette/', icon: 'layout' },
  { id: 'earth-tone-palette', name: 'Earth Tone Palette', description: 'Generate grounded earth tone palettes with natural browns and greens.', category: 'palette', slug: '/earth-tone-palette/', icon: 'swatch' },
  { id: 'flat-ui-palette', name: 'Flat UI Palette', description: 'Create modern flat UI color palettes for contemporary web design.', category: 'palette', slug: '/flat-ui-palette/', icon: 'layout' },
  { id: 'corporate-palette', name: 'Corporate Palette', description: 'Generate professional corporate color palettes for business branding.', category: 'palette', slug: '/corporate-palette/', icon: 'layout' },
  { id: 'luxury-palette', name: 'Luxury Palette', description: 'Create elegant luxury color palettes with sophisticated tones.', category: 'palette', slug: '/luxury-palette/', icon: 'swatch' },
  { id: 'gaming-palette', name: 'Gaming Palette', description: 'Generate energetic gaming color palettes for immersive experiences.', category: 'palette', slug: '/gaming-palette/', icon: 'swatch' },
  { id: 'ecommerce-palette', name: 'Ecommerce Palette', description: 'Create conversion-optimized color palettes for ecommerce stores.', category: 'palette', slug: '/ecommerce-palette/', icon: 'layout' },
  { id: 'dashboard-palette', name: 'Dashboard Palette', description: 'Generate data-friendly color palettes for dashboards and analytics.', category: 'palette', slug: '/dashboard-palette/', icon: 'layout' },
  { id: 'mobile-app-palette', name: 'Mobile App Palette', description: 'Create mobile-optimized color palettes for iOS and Android apps.', category: 'palette', slug: '/mobile-app-palette/', icon: 'layout' },
  { id: 'saas-palette', name: 'SaaS Palette', description: 'Generate SaaS product color palettes for modern web applications.', category: 'palette', slug: '/saas-palette/', icon: 'layout' },
  { id: 'logo-palette', name: 'Logo Palette', description: 'Create memorable color palettes designed for logo and brand identity.', category: 'palette', slug: '/logo-palette/', icon: 'swatch' },
  { id: 'fashion-palette', name: 'Fashion Palette', description: 'Generate trend-driven fashion color palettes for clothing and accessories.', category: 'palette', slug: '/fashion-palette/', icon: 'swatch' },
  { id: 'food-palette', name: 'Food Palette', description: 'Create appetizing food-inspired color palettes for culinary branding.', category: 'palette', slug: '/food-palette/', icon: 'swatch' },

  // ── Gradients ──
  { id: 'linear-gradient-generator', name: 'Linear Gradient Generator', description: 'Create smooth linear gradients with customizable direction and color stops.', category: 'gradient', slug: '/linear-gradient-generator/', icon: 'gradient' },
  { id: 'radial-gradient-generator', name: 'Radial Gradient Generator', description: 'Generate radial gradients that radiate from a central point.', category: 'gradient', slug: '/radial-gradient-generator/', icon: 'gradient' },
  { id: 'conic-gradient-generator', name: 'Conic Gradient Generator', description: 'Create conic gradients with rotating color transitions around a center.', category: 'gradient', slug: '/conic-gradient-generator/', icon: 'gradient' },
  { id: 'mesh-gradient-generator', name: 'Mesh Gradient Generator', description: 'Generate complex mesh gradients with multiple color control points.', category: 'gradient', slug: '/mesh-gradient-generator/', icon: 'gradient' },
  { id: 'css-gradient-generator', name: 'CSS Gradient Generator', description: 'Create CSS gradients with ready-to-use code for your stylesheets.', category: 'gradient', slug: '/css-gradient-generator/', icon: 'code' },
  { id: 'svg-gradient-generator', name: 'SVG Gradient Generator', description: 'Generate SVG gradients with linear and radial gradient definitions.', category: 'gradient', slug: '/svg-gradient-generator/', icon: 'code' },
  { id: 'animated-gradient-generator', name: 'Animated Gradient Generator', description: 'Create eye-catching animated gradients with smooth color transitions.', category: 'gradient', slug: '/animated-gradient-generator/', icon: 'gradient' },
  { id: 'text-gradient-generator', name: 'Text Gradient Generator', description: 'Apply beautiful gradient effects to text with CSS background-clip.', category: 'gradient', slug: '/text-gradient-generator/', icon: 'gradient' },
  { id: 'button-gradient-generator', name: 'Button Gradient Generator', description: 'Design gradient buttons with hover effects and custom styling.', category: 'gradient', slug: '/button-gradient-generator/', icon: 'gradient' },
  { id: 'background-gradient-generator', name: 'Background Gradient Generator', description: 'Create full-page background gradients for websites and apps.', category: 'gradient', slug: '/background-gradient-generator/', icon: 'gradient' },
  { id: 'gradient-border-generator', name: 'Gradient Border Generator', description: 'Apply gradient color transitions to element borders and outlines.', category: 'gradient', slug: '/gradient-border-generator/', icon: 'gradient' },
  { id: 'gradient-shadow-generator', name: 'Gradient Shadow Generator', description: 'Create gradient box shadows for depth and visual effects.', category: 'gradient', slug: '/gradient-shadow-generator/', icon: 'gradient' },
  { id: 'multi-stop-gradient', name: 'Multi-stop Gradient', description: 'Build complex gradients with multiple color stops for rich transitions.', category: 'gradient', slug: '/multi-stop-gradient/', icon: 'gradient' },
  { id: 'three-color-gradient', name: 'Three Color Gradient', description: 'Create gradients with three distinct color stops for richer blends.', category: 'gradient', slug: '/three-color-gradient/', icon: 'gradient' },
  { id: 'four-color-gradient', name: 'Four Color Gradient', description: 'Generate gradients using four colors for complex color transitions.', category: 'gradient', slug: '/four-color-gradient/', icon: 'gradient' },
  { id: 'gradient-mixer', name: 'Gradient Mixer', description: 'Mix and blend multiple colors into seamless gradient transitions.', category: 'gradient', slug: '/gradient-mixer/', icon: 'blend' },
  { id: 'gradient-reverser', name: 'Gradient Reverser', description: 'Reverse the color stop order of any gradient with one click.', category: 'gradient', slug: '/gradient-reverser/', icon: 'gradient' },
  { id: 'gradient-angle-generator', name: 'Gradient Angle Generator', description: 'Fine-tune gradient angles for precise directional color transitions.', category: 'gradient', slug: '/gradient-angle-generator/', icon: 'gradient' },
  { id: 'gradient-preview', name: 'Gradient Preview', description: 'Preview gradients in real-time across different screen sizes and contexts.', category: 'gradient', slug: '/gradient-preview/', icon: 'eye' },
  { id: 'gradient-exporter', name: 'Gradient Exporter', description: 'Export gradients as CSS, SVG, PNG, or other common formats.', category: 'gradient', slug: '/gradient-exporter/', icon: 'code' },
  { id: 'tailwind-gradient-generator', name: 'Tailwind Gradient Generator', description: 'Create gradients using Tailwind CSS gradient utility classes.', category: 'gradient', slug: '/tailwind-gradient-generator/', icon: 'code' },
  { id: 'bootstrap-gradient-generator', name: 'Bootstrap Gradient Generator', description: 'Generate gradients compatible with Bootstrap CSS framework.', category: 'gradient', slug: '/bootstrap-gradient-generator/', icon: 'code' },
  { id: 'glass-gradient-generator', name: 'Glass Gradient Generator', description: 'Create glassmorphism-style gradients with frosted glass effects.', category: 'gradient', slug: '/glass-gradient-generator/', icon: 'gradient' },
  { id: 'aurora-gradient-generator', name: 'Aurora Gradient Generator', description: 'Generate aurora borealis-inspired gradients with flowing colors.', category: 'gradient', slug: '/aurora-gradient-generator/', icon: 'gradient' },
  { id: 'metallic-gradient-generator', name: 'Metallic Gradient Generator', description: 'Create shiny metallic gradients that simulate gold, silver, and bronze.', category: 'gradient', slug: '/metallic-gradient-generator/', icon: 'gradient' },
  { id: 'neon-gradient-generator', name: 'Neon Gradient Generator', description: 'Generate bright neon gradients with electric glowing color effects.', category: 'gradient', slug: '/neon-gradient-generator/', icon: 'gradient' },
  { id: 'pastel-gradient-generator', name: 'Pastel Gradient Generator', description: 'Create soft pastel gradients with gentle color transitions.', category: 'gradient', slug: '/pastel-gradient-generator/', icon: 'gradient' },
  { id: 'instagram-gradient-generator', name: 'Instagram Gradient Generator', description: 'Generate Instagram-style gradients for stories and social media.', category: 'gradient', slug: '/instagram-gradient-generator/', icon: 'gradient' },
  { id: 'gradient-noise-generator', name: 'Gradient Noise Generator', description: 'Add organic noise textures to gradients for a natural look.', category: 'gradient', slug: '/gradient-noise-generator/', icon: 'gradient' },
  { id: 'grain-gradient-generator', name: 'Grain Gradient Generator', description: 'Create grainy gradient textures with subtle noise overlay effects.', category: 'gradient', slug: '/grain-gradient-generator/', icon: 'gradient' },
  { id: 'svg-mesh-generator', name: 'SVG Mesh Generator', description: 'Generate SVG mesh gradients with customizable control point grids.', category: 'gradient', slug: '/svg-mesh-generator/', icon: 'gradient' },
  { id: 'gradient-animation-builder', name: 'Gradient Animation Builder', description: 'Build animated gradient transitions with keyframe controls.', category: 'gradient', slug: '/gradient-animation-builder/', icon: 'gradient' },
  { id: 'gradient-overlay-generator', name: 'Gradient Overlay Generator', description: 'Create gradient overlays for images, videos, and interface elements.', category: 'gradient', slug: '/gradient-overlay-generator/', icon: 'gradient' },
  { id: 'gradient-code-generator', name: 'Gradient Code Generator', description: 'Generate production-ready CSS gradient code for your project.', category: 'gradient', slug: '/gradient-code-generator/', icon: 'code' },
  { id: 'gradient-library', name: 'Gradient Library', description: 'Browse a curated library of beautiful pre-made gradients.', category: 'gradient', slug: '/gradient-library/', icon: 'swatch' },

  // ── Accessibility ──
  { id: 'wcag-contrast-checker', name: 'WCAG Contrast Checker', description: 'Check color contrast ratios against WCAG 2.2 accessibility standards.', category: 'accessibility', slug: '/wcag-contrast-checker/', icon: 'contrast' },
  { id: 'apca-contrast-checker', name: 'APCA Contrast Checker', description: 'Evaluate contrast using the Advanced Perceptual Contrast Algorithm.', category: 'accessibility', slug: '/apca-contrast-checker/', icon: 'contrast' },
  { id: 'aaa-contrast-checker', name: 'AAA Contrast Checker', description: 'Verify color pairs meet the strictest WCAG AAA compliance level.', category: 'accessibility', slug: '/aaa-contrast-checker/', icon: 'contrast' },
  { id: 'aa-contrast-checker', name: 'AA Contrast Checker', description: 'Check color combinations against WCAG AA standards for accessibility.', category: 'accessibility', slug: '/aa-contrast-checker/', icon: 'contrast' },
  { id: 'color-blindness-simulator', name: 'Color Blindness Simulator', description: 'Preview your designs through the eyes of users with color blindness.', category: 'accessibility', slug: '/color-blindness-simulator/', icon: 'eye' },
  { id: 'protanopia-simulator', name: 'Protanopia Simulator', description: 'Simulate how colors appear to users with protanopia red-blindness.', category: 'accessibility', slug: '/protanopia-simulator/', icon: 'eye' },
  { id: 'deuteranopia-simulator', name: 'Deuteranopia Simulator', description: 'Simulate how colors appear to users with deuteranopia green-blindness.', category: 'accessibility', slug: '/deuteranopia-simulator/', icon: 'eye' },
  { id: 'tritanopia-simulator', name: 'Tritanopia Simulator', description: 'Simulate how colors appear to users with tritanopia blue-blindness.', category: 'accessibility', slug: '/tritanopia-simulator/', icon: 'eye' },
  { id: 'monochrome-preview', name: 'Monochrome Preview', description: 'Preview your designs in grayscale to test contrast and readability.', category: 'accessibility', slug: '/monochrome-preview/', icon: 'eye' },
  { id: 'readability-checker', name: 'Readability Checker', description: 'Assess text readability based on color contrast and font choices.', category: 'accessibility', slug: '/readability-checker/', icon: 'eye' },
  { id: 'accessible-palette-generator', name: 'Accessible Palette Generator', description: 'Generate color palettes that meet WCAG accessibility requirements.', category: 'accessibility', slug: '/accessible-palette-generator/', icon: 'swatch' },
  { id: 'accessible-gradient-generator', name: 'Accessible Gradient Generator', description: 'Create gradients that maintain sufficient contrast throughout.', category: 'accessibility', slug: '/accessible-gradient-generator/', icon: 'gradient' },
  { id: 'text-contrast-generator', name: 'Text Contrast Generator', description: 'Find text colors that meet contrast requirements against any background.', category: 'accessibility', slug: '/text-contrast-generator/', icon: 'contrast' },
  { id: 'background-contrast-generator', name: 'Background Contrast Generator', description: 'Generate accessible background colors for any foreground text color.', category: 'accessibility', slug: '/background-contrast-generator/', icon: 'contrast' },
  { id: 'button-accessibility-checker', name: 'Button Accessibility Checker', description: 'Verify button color combinations meet accessibility standards.', category: 'accessibility', slug: '/button-accessibility-checker/', icon: 'eye' },
  { id: 'link-accessibility-checker', name: 'Link Accessibility Checker', description: 'Check link color contrast against surrounding text and backgrounds.', category: 'accessibility', slug: '/link-accessibility-checker/', icon: 'eye' },
  { id: 'ui-accessibility-tester', name: 'UI Accessibility Tester', description: 'Test entire UI component color schemes for accessibility compliance.', category: 'accessibility', slug: '/ui-accessibility-tester/', icon: 'eye' },
  { id: 'dashboard-accessibility-checker', name: 'Dashboard Accessibility Checker', description: 'Evaluate dashboard color schemes for data visualization accessibility.', category: 'accessibility', slug: '/dashboard-accessibility-checker/', icon: 'eye' },
  { id: 'accessibility-report-generator', name: 'Accessibility Report Generator', description: 'Generate comprehensive accessibility reports for your color choices.', category: 'accessibility', slug: '/accessibility-report-generator/', icon: 'code' },
  { id: 'contrast-matrix-generator', name: 'Contrast Matrix Generator', description: 'Compare contrast ratios across multiple color pairs in a matrix view.', category: 'accessibility', slug: '/contrast-matrix-generator/', icon: 'contrast' },
  { id: 'color-vision-test', name: 'Color Vision Test', description: 'Test your own color vision with interactive color discrimination tests.', category: 'accessibility', slug: '/color-vision-test/', icon: 'eye' },
  { id: 'accessibility-heatmap', name: 'Accessibility Heatmap', description: 'Visualize accessibility issues across your color palette with a heatmap.', category: 'accessibility', slug: '/accessibility-heatmap/', icon: 'eye' },
  { id: 'contrast-fix-generator', name: 'Contrast Fix Generator', description: 'Automatically suggest color adjustments to fix contrast failures.', category: 'accessibility', slug: '/contrast-fix-generator/', icon: 'wand' },
  { id: 'dark-mode-contrast-checker', name: 'Dark Mode Contrast Checker', description: 'Verify color contrast ratios specifically for dark mode interfaces.', category: 'accessibility', slug: '/dark-mode-contrast-checker/', icon: 'contrast' },
  { id: 'light-mode-contrast-checker', name: 'Light Mode Contrast Checker', description: 'Verify color contrast ratios for light mode interface designs.', category: 'accessibility', slug: '/light-mode-contrast-checker/', icon: 'contrast' },
  { id: 'font-color-recommender', name: 'Font Color Recommender', description: 'Get accessible font color recommendations for any background color.', category: 'accessibility', slug: '/font-color-recommender/', icon: 'eye' },
  { id: 'background-color-recommender', name: 'Background Color Recommender', description: 'Find accessible background colors that work with your text colors.', category: 'accessibility', slug: '/background-color-recommender/', icon: 'eye' },
  { id: 'color-compliance-checker', name: 'Color Compliance Checker', description: 'Comprehensive color compliance checking against global standards.', category: 'accessibility', slug: '/color-compliance-checker/', icon: 'contrast' },
  { id: 'wcag-report-exporter', name: 'WCAG Report Exporter', description: 'Export detailed WCAG compliance reports for your color palette.', category: 'accessibility', slug: '/wcag-report-exporter/', icon: 'code' },
  { id: 'accessibility-palette-optimizer', name: 'Accessibility Palette Optimizer', description: 'Optimize your color palette to maximize accessibility compliance.', category: 'accessibility', slug: '/accessibility-palette-optimizer/', icon: 'wand' },

  // ── Image ──
  { id: 'image-palette-extractor', name: 'Image Palette Extractor', description: 'Extract a complete color palette from any uploaded image.', category: 'image', slug: '/image-palette-extractor/', icon: 'image' },
  { id: 'dominant-color-extractor', name: 'Dominant Color Extractor', description: 'Find the most dominant colors present in any image.', category: 'image', slug: '/dominant-color-extractor/', icon: 'image' },
  { id: 'average-color-finder', name: 'Average Color Finder', description: 'Calculate the average color of an entire image or region.', category: 'image', slug: '/average-color-finder/', icon: 'image' },
  { id: 'logo-color-extractor', name: 'Logo Color Extractor', description: 'Extract brand colors from company logo images accurately.', category: 'image', slug: '/logo-color-extractor/', icon: 'image' },
  { id: 'website-screenshot-color-extractor', name: 'Website Screenshot Color Extractor', description: 'Capture website screenshots and extract their color palettes.', category: 'image', slug: '/website-screenshot-color-extractor/', icon: 'image' },
  { id: 'image-gradient-generator', name: 'Image Gradient Generator', description: 'Create gradients inspired by colors found in your images.', category: 'image', slug: '/image-gradient-generator/', icon: 'gradient' },
  { id: 'image-to-css-gradient', name: 'Image to CSS Gradient', description: 'Convert image colors into CSS gradient code automatically.', category: 'image', slug: '/image-to-css-gradient/', icon: 'gradient' },
  { id: 'image-color-histogram', name: 'Image Color Histogram', description: 'Visualize the color distribution of any image with a histogram.', category: 'image', slug: '/image-color-histogram/', icon: 'image' },
  { id: 'color-cluster-analyzer', name: 'Color Cluster Analyzer', description: 'Analyze color clusters in images to identify color groups.', category: 'image', slug: '/color-cluster-analyzer/', icon: 'image' },
  { id: 'background-color-detector', name: 'Background Color Detector', description: 'Detect the primary background color in any image.', category: 'image', slug: '/background-color-detector/', icon: 'image' },
  { id: 'transparent-color-detector', name: 'Transparent Color Detector', description: 'Identify transparent areas and their underlying colors in images.', category: 'image', slug: '/transparent-color-detector/', icon: 'image' },
  { id: 'photo-palette-generator', name: 'Photo Palette Generator', description: 'Generate beautiful color palettes from your photo collections.', category: 'image', slug: '/photo-palette-generator/', icon: 'image' },
  { id: 'pixel-analyzer', name: 'Pixel Analyzer', description: 'Analyze individual pixel colors in uploaded images with zoom.', category: 'image', slug: '/pixel-analyzer/', icon: 'image' },
  { id: 'image-color-counter', name: 'Image Color Counter', description: 'Count the number of distinct colors used in any image.', category: 'image', slug: '/image-color-counter/', icon: 'image' },
  { id: 'brand-color-finder', name: 'Brand Color Finder', description: 'Identify brand colors from product images and marketing materials.', category: 'image', slug: '/brand-color-finder/', icon: 'image' },
  { id: 'image-theme-generator', name: 'Image Theme Generator', description: 'Generate themed color palettes based on the mood of your images.', category: 'image', slug: '/image-theme-generator/', icon: 'image' },
  { id: 'color-balance-analyzer', name: 'Color Balance Analyzer', description: 'Analyze the color balance and temperature distribution in images.', category: 'image', slug: '/color-balance-analyzer/', icon: 'image' },
  { id: 'saturation-analyzer', name: 'Saturation Analyzer', description: 'Measure the saturation levels across different areas of an image.', category: 'image', slug: '/saturation-analyzer/', icon: 'image' },
  { id: 'brightness-analyzer', name: 'Brightness Analyzer', description: 'Analyze the brightness distribution and exposure of images.', category: 'image', slug: '/brightness-analyzer/', icon: 'sun' },
  { id: 'vibrance-analyzer', name: 'Vibrance Analyzer', description: 'Measure the vibrance and color intensity of images.', category: 'image', slug: '/vibrance-analyzer/', icon: 'image' },
  { id: 'color-temperature-detector', name: 'Color Temperature Detector', description: 'Detect warm and cool color temperatures in images.', category: 'image', slug: '/color-temperature-detector/', icon: 'thermometer' },
  { id: 'shadow-detector', name: 'Shadow Detector', description: 'Identify shadow regions and their color characteristics in images.', category: 'image', slug: '/shadow-detector/', icon: 'image' },
  { id: 'highlight-detector', name: 'Highlight Detector', description: 'Detect highlight areas and their color values in images.', category: 'image', slug: '/highlight-detector/', icon: 'sun' },
  { id: 'image-mood-generator', name: 'Image Mood Generator', description: 'Analyze the emotional mood of images based on color composition.', category: 'image', slug: '/image-mood-generator/', icon: 'image' },
  { id: 'image-accent-color-finder', name: 'Image Accent Color Finder', description: 'Find accent colors that complement the dominant tones in images.', category: 'image', slug: '/image-accent-color-finder/', icon: 'image' },
  { id: 'ui-screenshot-palette', name: 'UI Screenshot Palette', description: 'Extract design system colors from UI screenshot images.', category: 'image', slug: '/ui-screenshot-palette/', icon: 'image' },
  { id: 'icon-palette-extractor', name: 'Icon Palette Extractor', description: 'Extract color palettes from icon sets and SVG files.', category: 'image', slug: '/icon-palette-extractor/', icon: 'image' },
  { id: 'artwork-palette-generator', name: 'Artwork Palette Generator', description: 'Generate color palettes inspired by famous artworks and illustrations.', category: 'image', slug: '/artwork-palette-generator/', icon: 'image' },
  { id: 'wallpaper-palette-extractor', name: 'Wallpaper Palette Extractor', description: 'Extract color schemes from wallpaper images for theme design.', category: 'image', slug: '/wallpaper-palette-extractor/', icon: 'image' },
  { id: 'batch-image-color-extractor', name: 'Batch Image Color Extractor', description: 'Process multiple images at once to extract their color palettes.', category: 'image', slug: '/batch-image-color-extractor/', icon: 'image' },

  // ── Adjustments ──
  { id: 'tint-generator', name: 'Tint Generator', description: 'Generate lighter tints of any color by adding white.', category: 'adjustment', slug: '/tint-generator/', icon: 'sun' },
  { id: 'shade-generator', name: 'Shade Generator', description: 'Generate darker shades of any color by adding black.', category: 'adjustment', slug: '/shade-generator/', icon: 'sun' },
  { id: 'tone-generator', name: 'Tone Generator', description: 'Generate muted tones of any color by adding gray.', category: 'adjustment', slug: '/tone-generator/', icon: 'adjust' },
  { id: 'saturation-adjuster', name: 'Saturation Adjuster', description: 'Increase or decrease the saturation intensity of any color.', category: 'adjustment', slug: '/saturation-adjuster/', icon: 'adjust' },
  { id: 'brightness-adjuster', name: 'Brightness Adjuster', description: 'Adjust the brightness level of any color value.', category: 'adjustment', slug: '/brightness-adjuster/', icon: 'sun' },
  { id: 'contrast-adjuster', name: 'Contrast Adjuster', description: 'Fine-tune the contrast between color elements in your design.', category: 'adjustment', slug: '/contrast-adjuster/', icon: 'contrast' },
  { id: 'hue-rotator', name: 'Hue Rotator', description: 'Rotate the hue of any color around the color wheel.', category: 'adjustment', slug: '/hue-rotator/', icon: 'adjust' },
  { id: 'vibrance-adjuster', name: 'Vibrance Adjuster', description: 'Adjust vibrance to enhance or reduce color intensity smartly.', category: 'adjustment', slug: '/vibrance-adjuster/', icon: 'adjust' },
  { id: 'gamma-adjuster', name: 'Gamma Adjuster', description: 'Apply gamma correction to colors for proper display calibration.', category: 'adjustment', slug: '/gamma-adjuster/', icon: 'adjust' },
  { id: 'opacity-generator', name: 'Opacity Generator', description: 'Generate colors at different opacity levels for layered designs.', category: 'adjustment', slug: '/opacity-generator/', icon: 'adjust' },
  { id: 'alpha-adjuster', name: 'Alpha Adjuster', description: 'Adjust the alpha transparency channel of any color.', category: 'adjustment', slug: '/alpha-adjuster/', icon: 'adjust' },
  { id: 'lighten-color', name: 'Lighten Color', description: 'Lighten any color by a specified percentage amount.', category: 'adjustment', slug: '/lighten-color/', icon: 'sun' },
  { id: 'darken-color', name: 'Darken Color', description: 'Darken any color by a specified percentage amount.', category: 'adjustment', slug: '/darken-color/', icon: 'sun' },
  { id: 'desaturate-color', name: 'Desaturate Color', description: 'Reduce the saturation of any color toward grayscale.', category: 'adjustment', slug: '/desaturate-color/', icon: 'adjust' },
  { id: 'invert-color', name: 'Invert Color', description: 'Invert any color to its opposite on the color wheel.', category: 'adjustment', slug: '/invert-color/', icon: 'adjust' },
  { id: 'grayscale-generator', name: 'Grayscale Generator', description: 'Convert any color to its grayscale equivalent.', category: 'adjustment', slug: '/grayscale-generator/', icon: 'adjust' },
  { id: 'sepia-generator', name: 'Sepia Generator', description: 'Apply a vintage sepia tone effect to any color.', category: 'adjustment', slug: '/sepia-generator/', icon: 'adjust' },
  { id: 'temperature-adjuster', name: 'Temperature Adjuster', description: 'Shift color temperature between warm and cool tones.', category: 'adjustment', slug: '/temperature-adjuster/', icon: 'thermometer' },
  { id: 'color-mixer', name: 'Color Mixer', description: 'Mix two or more colors together and preview the result.', category: 'adjustment', slug: '/color-mixer/', icon: 'blend' },
  { id: 'blend-mode-simulator', name: 'Blend Mode Simulator', description: 'Simulate CSS blend modes between foreground and background colors.', category: 'adjustment', slug: '/blend-mode-simulator/', icon: 'blend' },
  { id: 'overlay-color-generator', name: 'Overlay Color Generator', description: 'Generate overlay color effects for layering on images and elements.', category: 'adjustment', slug: '/overlay-color-generator/', icon: 'blend' },
  { id: 'multiply-blend-generator', name: 'Multiply Blend Generator', description: 'Apply multiply blend mode effects between two colors.', category: 'adjustment', slug: '/multiply-blend-generator/', icon: 'blend' },
  { id: 'screen-blend-generator', name: 'Screen Blend Generator', description: 'Apply screen blend mode effects for brightening color combinations.', category: 'adjustment', slug: '/screen-blend-generator/', icon: 'blend' },
  { id: 'soft-light-generator', name: 'Soft Light Generator', description: 'Create soft light blending effects between colors.', category: 'adjustment', slug: '/soft-light-generator/', icon: 'blend' },
  { id: 'hard-light-generator', name: 'Hard Light Generator', description: 'Create hard light blending effects for dramatic color results.', category: 'adjustment', slug: '/hard-light-generator/', icon: 'blend' },
  { id: 'color-dodge-generator', name: 'Color Dodge Generator', description: 'Apply color dodge blending to brighten and lighten colors.', category: 'adjustment', slug: '/color-dodge-generator/', icon: 'blend' },
  { id: 'burn-generator', name: 'Burn Generator', description: 'Apply burn blending effects to darken and enrich colors.', category: 'adjustment', slug: '/burn-generator/', icon: 'blend' },
  { id: 'color-harmonizer', name: 'Color Harmonizer', description: 'Automatically adjust colors to create harmonious combinations.', category: 'adjustment', slug: '/color-harmonizer/', icon: 'wand' },
  { id: 'dynamic-theme-generator', name: 'Dynamic Theme Generator', description: 'Generate dynamic color themes that adapt to user preferences.', category: 'adjustment', slug: '/dynamic-theme-generator/', icon: 'wand' },
  { id: 'color-equalizer', name: 'Color Equalizer', description: 'Fine-tune individual color channels with an equalizer interface.', category: 'adjustment', slug: '/color-equalizer/', icon: 'adjust' },

  // ── Reference ──
  { id: 'css-named-colors', name: 'CSS Named Colors', description: 'Browse all 148 CSS named colors with hex values and previews.', category: 'reference', slug: '/css-named-colors/', icon: 'swatch' },
  { id: 'html-named-colors', name: 'HTML Named Colors', description: 'Explore all HTML color names with their corresponding hex codes.', category: 'reference', slug: '/html-named-colors/', icon: 'swatch' },
  { id: 'tailwind-colors', name: 'Tailwind Colors', description: 'Browse the complete Tailwind CSS color palette with all shades.', category: 'reference', slug: '/tailwind-colors/', icon: 'swatch' },
  { id: 'material-colors', name: 'Material Colors', description: 'Explore the full Material Design 3 color system and palette.', category: 'reference', slug: '/material-colors/', icon: 'swatch' },
  { id: 'bootstrap-colors', name: 'Bootstrap Colors', description: 'Browse all Bootstrap 5 default color variables and utility classes.', category: 'reference', slug: '/bootstrap-colors/', icon: 'swatch' },
  { id: 'brand-colors-database', name: 'Brand Colors Database', description: 'Search through a database of official brand color codes from top companies.', category: 'reference', slug: '/brand-colors-database/', icon: 'swatch' },
  { id: 'country-flag-colors', name: 'Country Flag Colors', description: 'Explore the official colors used in national flags around the world.', category: 'reference', slug: '/country-flag-colors/', icon: 'swatch' },
  { id: 'google-colors', name: 'Google Colors', description: 'Browse official Google brand colors and product palette references.', category: 'reference', slug: '/google-colors/', icon: 'swatch' },
  { id: 'apple-colors', name: 'Apple Colors', description: 'Explore Apple design system colors and brand palette references.', category: 'reference', slug: '/apple-colors/', icon: 'swatch' },
  { id: 'microsoft-colors', name: 'Microsoft Colors', description: 'Browse official Microsoft brand colors and Fluent Design palette.', category: 'reference', slug: '/microsoft-colors/', icon: 'swatch' },
  { id: 'discord-colors', name: 'Discord Colors', description: 'Explore Discord brand colors and UI theme color references.', category: 'reference', slug: '/discord-colors/', icon: 'swatch' },
  { id: 'youtube-colors', name: 'YouTube Colors', description: 'Browse YouTube brand colors and platform color references.', category: 'reference', slug: '/youtube-colors/', icon: 'swatch' },
  { id: 'x-brand-colors', name: 'X Brand Colors', description: 'Explore the official X (formerly Twitter) brand color palette.', category: 'reference', slug: '/x-brand-colors/', icon: 'swatch' },
  { id: 'instagram-colors', name: 'Instagram Colors', description: 'Browse Instagram brand colors and gradient palette references.', category: 'reference', slug: '/instagram-colors/', icon: 'swatch' },
  { id: 'spotify-colors', name: 'Spotify Colors', description: 'Explore Spotify brand colors and music-themed palette references.', category: 'reference', slug: '/spotify-colors/', icon: 'swatch' },
  { id: 'netflix-colors', name: 'Netflix Colors', description: 'Browse Netflix brand colors and entertainment palette references.', category: 'reference', slug: '/netflix-colors/', icon: 'swatch' },
  { id: 'fifa-team-colors', name: 'FIFA Team Colors', description: 'Explore official colors from FIFA World Cup national football teams.', category: 'reference', slug: '/fifa-team-colors/', icon: 'swatch' },
  { id: 'nba-team-colors', name: 'NBA Team Colors', description: 'Browse official NBA team colors and basketball brand palettes.', category: 'reference', slug: '/nba-team-colors/', icon: 'swatch' },
  { id: 'premier-league-colors', name: 'Premier League Colors', description: 'Explore official Premier League football club color schemes.', category: 'reference', slug: '/premier-league-colors/', icon: 'swatch' },
  { id: 'national-flag-colors', name: 'National Flag Colors', description: 'Search the official colors of national flags from every country.', category: 'reference', slug: '/national-flag-colors/', icon: 'swatch' },
  { id: 'web-safe-colors', name: 'Web Safe Colors', description: 'Browse the 216 web-safe color palette for legacy browser support.', category: 'reference', slug: '/web-safe-colors/', icon: 'swatch' },
  { id: 'pantone-finder', name: 'Pantone Finder', description: 'Find Pantone color matches and equivalents for any color value.', category: 'reference', slug: '/pantone-finder/', icon: 'search' },
  { id: 'ral-color-finder', name: 'RAL Color Finder', description: 'Find RAL classic color codes and their nearest color equivalents.', category: 'reference', slug: '/ral-color-finder/', icon: 'search' },
  { id: 'ncs-color-finder', name: 'NCS Color Finder', description: 'Find Natural Color System codes and their color representations.', category: 'reference', slug: '/ncs-color-finder/', icon: 'search' },
  { id: 'css-color-names-search', name: 'CSS Color Names Search', description: 'Search through all CSS color names by keyword or hex value.', category: 'reference', slug: '/css-color-names-search/', icon: 'search' },
  { id: 'color-meaning-guide', name: 'Color Meaning Guide', description: 'Learn the psychological meanings and cultural associations of colors.', category: 'reference', slug: '/color-meaning-guide/', icon: 'search' },
  { id: 'psychological-colors-guide', name: 'Psychological Colors Guide', description: 'Explore how colors affect mood, behavior, and perception in design.', category: 'reference', slug: '/psychological-colors-guide/', icon: 'search' },
  { id: 'ui-color-library', name: 'UI Color Library', description: 'Browse a curated library of color schemes for user interface design.', category: 'reference', slug: '/ui-color-library/', icon: 'swatch' },
  { id: 'seasonal-color-library', name: 'Seasonal Color Library', description: 'Explore color palettes inspired by each season of the year.', category: 'reference', slug: '/seasonal-color-library/', icon: 'swatch' },
  { id: 'color-trends', name: 'Color Trends', description: 'Discover current and upcoming color trends in design and branding.', category: 'reference', slug: '/color-trends/', icon: 'swatch' },
  { id: 'design-tokens-library', name: 'Design Tokens Library', description: 'Browse reference color design tokens for design system development.', category: 'reference', slug: '/design-tokens-library/', icon: 'swatch' },
  { id: 'semantic-color-library', name: 'Semantic Color Library', description: 'Explore semantic color naming conventions for design systems.', category: 'reference', slug: '/semantic-color-library/', icon: 'swatch' },
  { id: 'status-color-library', name: 'Status Color Library', description: 'Browse color conventions for success, warning, error, and info states.', category: 'reference', slug: '/status-color-library/', icon: 'swatch' },
  { id: 'neutral-color-library', name: 'Neutral Color Library', description: 'Explore neutral color palettes for grays, whites, and blacks.', category: 'reference', slug: '/neutral-color-library/', icon: 'swatch' },
  { id: 'pastel-library', name: 'Pastel Library', description: 'Browse a collection of soft pastel colors for gentle design aesthetics.', category: 'reference', slug: '/pastel-library/', icon: 'swatch' },

  // ── Utilities ──
  { id: 'color-name-finder', name: 'Color Name Finder', description: 'Find the human-readable name of any color from its hex or RGB value.', category: 'utility', slug: '/color-name-finder/', icon: 'search' },
  { id: 'color-similarity-checker', name: 'Color Similarity Checker', description: 'Measure how similar or different two colors are from each other.', category: 'utility', slug: '/color-similarity-checker/', icon: 'search' },
  { id: 'duplicate-color-finder', name: 'Duplicate Color Finder', description: 'Find and identify duplicate colors within your palette or list.', category: 'utility', slug: '/duplicate-color-finder/', icon: 'search' },
  { id: 'color-difference-calculator', name: 'Color Difference (Delta E) Calculator', description: 'Calculate the Delta E perceptual difference between two colors.', category: 'utility', slug: '/color-difference-calculator/', icon: 'code' },
  { id: 'random-color-generator', name: 'Random Color Generator', description: 'Generate random colors with hex, RGB, and HSL values on demand.', category: 'utility', slug: '/random-color-generator/', icon: 'wand' },
  { id: 'color-wheel', name: 'Color Wheel', description: 'Explore color relationships with an interactive color wheel tool.', category: 'utility', slug: '/color-wheel/', icon: 'palette' },
  { id: 'palette-exporter', name: 'Palette Exporter', description: 'Export your color palettes in CSS, SCSS, JSON, and other formats.', category: 'utility', slug: '/palette-exporter/', icon: 'code' },
  { id: 'palette-importer', name: 'Palette Importer', description: 'Import color palettes from CSS, JSON, SCSS, and other file formats.', category: 'utility', slug: '/palette-importer/', icon: 'code' },
  { id: 'css-variable-generator', name: 'CSS Variable Generator', description: 'Generate CSS custom property definitions from your color palette.', category: 'utility', slug: '/css-variable-generator/', icon: 'code' },
  { id: 'tailwind-theme-generator', name: 'Tailwind Theme Generator', description: 'Generate Tailwind CSS theme configuration from your color palette.', category: 'utility', slug: '/tailwind-theme-generator/', icon: 'code' },
  { id: 'figma-color-export', name: 'Figma Color Export', description: 'Export your color palettes in Figma-compatible format.', category: 'utility', slug: '/figma-color-export/', icon: 'code' },
  { id: 'adobe-ase-export', name: 'Adobe ASE Export', description: 'Export color palettes as Adobe Swatch Exchange (.ase) files.', category: 'utility', slug: '/adobe-ase-export/', icon: 'code' },
  { id: 'scss-variables-generator', name: 'SCSS Variables Generator', description: 'Generate SCSS variable definitions from your color palette.', category: 'utility', slug: '/scss-variables-generator/', icon: 'code' },
  { id: 'json-palette-generator', name: 'JSON Palette Generator', description: 'Generate structured JSON palette files for your design system.', category: 'utility', slug: '/json-palette-generator/', icon: 'code' },
  { id: 'android-colors-xml-generator', name: 'Android Colors.xml Generator', description: 'Generate Android colors.xml resource files from your palette.', category: 'utility', slug: '/android-colors-xml-generator/', icon: 'code' },
  { id: 'swift-color-assets-generator', name: 'Swift Color Assets Generator', description: 'Generate Swift color asset definitions for iOS development.', category: 'utility', slug: '/swift-color-assets-generator/', icon: 'code' },
  { id: 'flutter-theme-generator', name: 'Flutter Theme Generator', description: 'Generate Flutter ThemeData color configuration from your palette.', category: 'utility', slug: '/flutter-theme-generator/', icon: 'code' },
  { id: 'react-theme-generator', name: 'React Theme Generator', description: 'Generate React theme provider configuration from color palettes.', category: 'utility', slug: '/react-theme-generator/', icon: 'code' },
  { id: 'design-token-generator', name: 'Design Token Generator', description: 'Generate cross-platform design tokens from your color palette.', category: 'utility', slug: '/design-token-generator/', icon: 'code' },
  { id: 'color-playground', name: 'Color Playground', description: 'Experiment with colors interactively in a free-form playground.', category: 'utility', slug: '/color-playground/', icon: 'wand' },
]
